# loads default configuration do not remove
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http: !include http.yaml
mqtt: !include mqtt.yaml
recorder: !include recorder.yaml

