api:
  insecure: true
  dashboard: true

log:
  filepath: /logs/traefik.log 
  level: {env.LOG_LEVEL}

accessLog:
  filePath: /log/access.log 
  bufferingSize: 100
  filters:
    statusCodes: 204-299,400-499,500-599

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    network: proxy
    swarmMode: false
  file:
    directory: /rules
    watch: true 

certificatesResolvers:
  dns-cloudflare:
    acme:
      email: '' # cloudflare email 
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare 
        resolvers: 
          - 1.1.1.1:53
          - 1.1.0.0.1:53
        delayBeforeCheck: 90

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: !!str ':80'
    http:
      redirections:
        entrypoint: 
          to: https
          scheme: https
          permanent: true
  https:
    address: !!str ':443'
    forwardedHeaders:
      trustedIPS: [ {env.TRUSTED_IPS} ]
    http:
      tls:
        options: tls-opts@file
        certresolver: dns-cloudflare
        domains:
          - main: example.tld
            sans: '*.example.tld'
  traefik:
    address: !!str ':8080'
  
