http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
        usersFile: /shared/.htpasswd
        realm: Traefik Basic Auth
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-https-redirect-scheme:
      redirectScheme:
        scheme: https 
        permanent: true
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: "allow-from https:{{env "DOMAINNAME_CLOUD_SERVER"}}"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin
        permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()
        customResponseHeaders:
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex,
          server: ''
    middlewares-compress:
      compress: {}
