version: '3.9'

########################## NETWORKS ################################
networks:
  default:
    driver: bridge
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET

########################## EXTENSION FIELDS ########################

x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-environment-umask: &umask-tz-puid-pgid
  <<: *default-tz-puid-pgid
  UMASK: $UMASK

x-common-keys-core: &common-keys-core
  networks:
    - proxy
  restart: always

x-common-keys-apps: &common-keys-apps
  networks:
    - proxy
  restart: unless-stopped

x-common-keys-media: &common-keys-media
  networks:
    - proxy
  restart: no

x-port-list: &port-list
  ports:
    - 80:80
    - 8080:8080 # traefik api

############################ SERVICES ###############################
services:
  homeassistant:
    <<: *common-keys-core
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      <<: *default-tz-puid-pgid
      HC_IGNORE_SSL: true
    privileged: true
    ports:
      - 8123:8123/tcp
      - 8124:8124/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - $DOPT/homeassistant/themes/:/config/themes/:ro
      - $DOPT/homeassistant/www/:/config/www/:ro
      - $DOPT/homeassistant/configuration.yaml:/config/configuration.yaml:ro
      - $DOPT/homeassistant/automations.yaml:/config/automations.yaml:ro
      - $DOPT/homeassistant/http.yaml:/config/http.yaml:ro
      - $DOPT/homeassistant/mqtt.yaml:/config/mqtt.yaml:ro
      - $DOPT/homeassistant/recorder.yaml:/config/recorder.yaml:ro
      - $DOPT/homeassistant/scenes.yaml:/config/scenes.yaml:rw
      - $DOPT/homeassistant/scripts.yaml:/config/scripts.yaml:ro
      - $DAPPDATA/homeassistant/:/config/:rw
      - $DSECRETS/homeassistant.yaml:/config/secrets.yaml:ro
  netdata:
    <<: *common-keys-core
    container_name: netdata
    hostname: monitor.amandas.casa
    image: netdata/netdata:latest
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 8086:19999
    volumes:
      - $DAPPDATA/netdata/config:/etc/netdata:rw
      - $DAPPDATA/netdata/lib:/var/lib/netdata:rw
      - $DSHARED/netdata/cache:/var/cache/netdata:rw
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/host/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ## ---------- TCP/UDP Services ---------- ##
  mosquitto:
    <<: *common-keys-core
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 1883:1883/tcp
      - 1883:1883/udp
      - 9001:9001/tcp
      - 9001:9001/udp
    volumes:
      - $DOPT/mosquitto/:/mosquitto/config/:rw
      - $DAPPDATA/mosquitto/:/mosquitto/data/:rw
      - $DLOGS/mosquitto/:/mosquitto/log/:rw
  nodered:
    <<: *common-keys-core
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 1880:1880/tcp
      - 1880:1880/udp
    volumes:
      - $DAPPDATA/nodered/:/data/:rw
  cups:
    <<: *common-keys-apps
    container_name: cups
    build:
      context: $DCUSTOM/cups
      dockerfile: Dockerfile
    environment:
      <<: *default-tz-puid-pgid
      CUPSADMIN: $CUPSADMIN
      CUPSPASSWORD: $CUPSPASSWORD
    ports:
      - 631:631
    volumes:
      - /var/run/dbus/:/var/run/dbus/
      - $DAPPDATA/cups/config:/config
      - $DAPPDATA/cups/services:/services
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
  ## ---------- Media Center ---------- ##
  sonarr:
    <<: *common-keys-apps
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    ports:
      - 8989:8989
    volumes:
      - $DAPPDATA/sonarr/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/downloads/:/downloads/:rw
  radarr:
    <<: *common-keys-apps
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    ports:
      - 7878:7878
    volumes:
      - $DAPPDATA/radarr/:/config/:rw
      - $DMEDIA/movies/:/movies/:rw
      - $DMEDIA/downloads/:/downloads/:rw
  bazarr:
    <<: *common-keys-apps
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    ports:
      - 6767:6767
    volumes:
      - $DAPPDATA/bazarr/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/movies/:/movies/:rw
  prowlarr:
    <<: *common-keys-apps
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    ports:
      - 9696:9696
    volumes:
      - $DAPPDATA/prowlarr/:/config/:rw
  jellyfin:
    <<: *common-keys-apps
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      <<: *umask-tz-puid-pgid
      JELLYFIN_PublishedServerUrl: $JELLYFIN_SERVERURL
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096/tcp
      - 8096:8096/udp
      - 1900:1900/tcp
      - 1900:1900/udp
    volumes:
      - $DAPPDATA/jellyfin/:/config/:rw
      - $DMEDIA/tv/:/data/tvshows/:rw
      - $DMEDIA/movies/:/data/movies/:rw
  plex:
    <<: *common-keys-apps
    container_name: plex
    hostname: plex
    # comment next line if you are using AMD acceleration
    image: plexinc/pms-docker
    # uncomment next to build and use AMD acceleration
    # build:
    #   context: $DCUSTOM/plex
    #   dockerfile: ./amd.Dockerfile
    environment:
      <<: *umask-tz-puid-pgid
      VERSION: latest
      PLEX_CLAIM: $PLEX_CLAIM
      PLEX_PGID: $PGID
      PLEX_PUID: $PUID
      ADVERTISE_IP: plex.$DOMAIN
    devices:
      # Intel acceleration hardware enable
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3500:3500/tcp
      - 3500:3500/udp
      - 8324:8324/tcp
      - 8324:8324/udp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32411:32411/udp
      - 32412:32212/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - $DSHARED/transcode:/transcode:rw
      - $DAPPDATA/plex/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/movies/:/movies/:rw
  transmission:
    <<: *common-keys-apps
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      <<: *umask-tz-puid-pgid
      USER: $TRANSMISSION_USER
      PASS: $TRANSMISSION_PASS
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - $DAPPDATA/transmission/:/config/:rw
      - $DMEDIA/downloads/:/downloads/:rw
      - $DSHARED/watch/:/watch/:rw
  jdownloader2:
    <<: *common-keys-apps
    container_name: jdownloader2
    image: jlesage/jdownloader-2
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 5800:5800
    volumes:
      - $DAPPDATA/jdownloader2/:/config:rw
      - $DMEDIA/downloads/:/output:rw

  ## ---------- Management ---------- ##

  homarr:
    <<: *common-keys-apps
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 80:7575
    volumes:
      - $DAPPDATA/homarr/config/:/app/data/config/:rw
      - $DAPPDATA/homarr/data/:/data:rw
      - $DAPPDATA/homarr/icons/:/app/public/icons/:rw
  portainer:
    <<: *common-keys-core
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      <<: *default-tz-puid-pgid
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DAPPDATA/portainer/:/data/:rw
    ports:
      - 9000:9000
  filebrowser:
    <<: *common-keys-core
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    environment:
      <<: *default-tz-puid-pgid
    user: $PUID:$PGID
    ports:
      - 8081:8080
    volumes:
      - $DMEDIA/:/data/:rw
      - $DAPPDATA/filebrowser/:/config/:rw
  watchtower:
    <<: *common-keys-core
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      <<: *default-tz-puid-pgid
      WATCHTOWER_CLEANUP: $WATCHTOWER_CLEANUP
      WATCHTOWER_INCLUDE_RESTARTING: $WATCHTOWER_INCLUDE_RESTARTING
      WATCHTOWER_SCHEDULE: $WATCHTOWER_SCHEDULE
      WATCHTOWER_LOG_LEVEL: $LOG_LEVEL
      WATCHTOWER_ROLLING_RESTART: $WATCHTOWER_ROLLING_RESTART
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  adminer:
    <<: *common-keys-core
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    environment:
      <<: *default-tz-puid-pgid
      ADMINER_DEFAULT_SERVER: $ADMINER_DEFAULT_SERVER

  ## ---------- Home Automatization ---------- ##
  mosquitto-client:
    <<: *common-keys-core
    container_name: mosquitto-client
    image: emqx/mqttx-web:latest
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 8083:80
  zigbee2mqtt:
    <<: *common-keys-core
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    environment:
      <<: *default-tz-puid-pgid
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8084:8080
    volumes:
      - $DOPT/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml:rw
      - /run/udev:/run/udev:ro
      - $DAPPDATA/zigbee2mqtt/:/app/data/:rw
      - $DSCRIPTS/searchtty.sh:/app/searchtty.sh:ro
      - $DSECRETS/zigbee2mqtt.yaml:/app/data/secrets.yaml:ro

  ## ---------- Tools ---------- ##
  librespeed:
    <<: *common-keys-core
    container_name: librespeed
    image: lscr.io/linuxserver/librespeed:latest
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 8085:80
  znc:
    <<: *common-keys-core
    container_name: znc
    image: znc
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 6501:6501/tcp
      - 6502:6502/tcp
    volumes:
      - $DAPPDATA/znc:/znc-data:rw
  mariadb:
    <<: *common-keys-core
    container_name: mariadb
    image: mariadb
    environment:
      <<: *default-tz-puid-pgid
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_USERNAME: $MARIADB_BASE_USERNAME
      MYSQL_PASSWORD: $MARIADB_BASE_PASSWORD
    ports:
      - 3306:3306/tcp
    volumes:
      - $DAPPDATA/mariadb/:/var/lib/mysql
  mongodb:
    <<: *common-keys-core
    container_name: mongodb
    image: mongo
    environment:
      <<: *default-tz-puid-pgid
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports:
      - 27017:27017/tcp
    volumes:
      - $DAPPDATA/mongodb/:/data/db
  thelounge:
    <<: *common-keys-core
    container_name: thelounge
    image: thelounge/thelounge
    environment:
      <<: *default-tz-puid-pgid
    ports:
      - 8090:9000
    volumes:
      - $DAPPDATA/thelounge:/var/opt/thelounge
