version: '3.9'

########################## NETWORKS ################################
networks:
  default:
    driver: bridge
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET

########################## EXTENSION FIELDS ########################

x-dns: &dns-core
  dns:
    - 192.168.4.45
    - 8.8.8.8
    - 8.8.4.4 
    - 1.1.1.1 
    - 1.0.0.1
          
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-environment-umask: &umask-tz-puid-pgid
  <<: *default-tz-puid-pgid
  UMASK: $UMASK

x-common-keys-core: &common-keys-core
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: always

x-common-keys-with-dns-core: &common-keys-dns-core
  <<: *common-keys-core
  <<: *dns-core

x-common-keys-apps: &common-keys-apps
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  <<: *dns-core

x-common-keys-media: &common-keys-media
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: no 

############################ SERVICES ###############################
services:
  ## ---------- DNS Service ---------- ##
  dnsmasq:
    <<: *common-keys-core
    container_name: dnsmasq
    image: jpillora/dnsmasq:latest
    environment:
      <<: *default-tz-puid-pgid
      HTTP_USER: $DNSMASQ_USER
      HTTP_PASS: $DNSMASQ_PASS
    cap_add:
      - NET_ADMIN
    logging:
      options:
        max-size: 100m 
    volumes:
      - $DOPT/dnsmasq/dnsmasq.d/:/etc/dnsmasq.d/:rw
      - $DOPT/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro 

  ## ---------- TCP/UDP Services ---------- ##
  ventoy:
  mosquitto:
  modered:

  ## ---------- Media Center ---------- ##
  sonarr:
  radarr:
  bazarr:
  prowlarr:
  jellyfin:
  plex:
  transmission:

  ## ---------- Management ---------- ##
  homarr:
  portainer:
  traefik:
  filebrowser:
  watchtower:

  ## ---------- Home Automatization ---------- ##
  mosquitto-client:
  homeassitant:
  
  ## ---------- Tools ---------- ##
  librespeed:
  znc:
  thelounge:
  mariadb:
  mongodb: 
