version: '3.9'

########################## NETWORKS ################################
networks:
  default:
    driver: bridge
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET

########################## EXTENSION FIELDS ########################

x-dns: &dns-core
  dns:
    - 192.168.4.45
    - 8.8.8.8
    - 8.8.4.4 
    - 1.1.1.1 
    - 1.0.0.1
          
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-environment-umask: &umask-tz-puid-pgid
  <<: *default-tz-puid-pgid
  UMASK: $UMASK

x-common-keys-core: &common-keys-core
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: always

x-common-keys-with-dns-core: &common-keys-dns-core
  <<: *common-keys-core
  <<: *dns-core

x-common-keys-apps: &common-keys-apps
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  <<: *dns-core

x-common-keys-media: &common-keys-media
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
  restart: no 

############################ SERVICES ###############################
services:
  ## ---------- DNS Service ---------- ##
  dnsmasq:
    <<: *common-keys-core
    container_name: dnsmasq
    image: jpillora/dnsmasq:latest
    environment:
      <<: *default-tz-puid-pgid
      HTTP_USER: $DNSMASQ_USER
      HTTP_PASS: $DNSMASQ_PASS
    cap_add:
      - NET_ADMIN
    logging:
      options:
        max-size: 100m 
    volumes:
      - $DOPT/dnsmasq/dnsmasq.d/:/etc/dnsmasq.d/:rw
      - $DOPT/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro 

  ## ---------- TCP/UDP Services ---------- ##
  ventoy:
    <<: *common-keys-core
    container_name: ventoy
    image: thedrobe/inventoy-docker:latest
    environment:
      <<: *default-tz-puid-pgid
    privileged: true
    stop_signal: SIGINT
    volumes:
      - $DMEDIA/iso/:/app/iso/:ro
      - $DLOGS/ventoy/:/app/log/:rw
  mosquitto:
    <<: *common-keys-core
    container_name: mosquitto 
    image: eclipse-mosquitto:latest
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOPT/mosquitto/:/mosquitto/config/:rw
      - $DAPPDATA/mosquitto/:/mosquitto/data/:rw
      - $DLOGS/mosquitto/:/mosquitto/log/:rw
  nodered:
    <<: *common-keys-dns-core
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DAPPDATA/nodered/:/data/:rw
  ## ---------- Media Center ---------- ##
  sonarr:
    <<: *common-keys-apps
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    volumes:
      - $DAPPDATA/sonarr/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/downloads/:/downloads/:rw
  radarr:
    <<: *common-keys-apps
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    volumes:
      - $DAPPDATA/radarr/:/config/:rw
      - $DMEDIA/movies/:/movies/:rw
      - $DMEDIA/downloads/:/downloads/:rw
  bazarr:
    <<: *common-keys-apps
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    volumes:
      - $DAPPDATA/bazarr/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/movies/:/movies/:rw
  prowlarr:
    <<: *common-keys-apps
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      <<: *umask-tz-puid-pgid
    volumes:
      - $DAPPDATA/prowlarr/:/config/:rw
  jellyfin:
    <<: *common-keys-apps
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      <<: *umask-tz-puid-pgid
      JELLYFIN_PublishedServerUrl: $JELLYFIN_SERVERURL 
    volumes:
      - $DAPPDATA/jellyfin/:/config/:rw
      - $DMEDIA/tv/:/data/tvshows/:rw
      - $DMEDIA/movies/:/data/movies/:rw
  plex:
    <<: *common-keys-apps
    container_name: plex
    # comment next line if you are using AMD acceleration 
    image: lscr.io/linuxserver/plex:latest
    # uncomment next to build and use AMD acceleration
    # build:
    #   context: $DCUSTOM/plex
    #   dockerfile: ./amd.Dockerfile 
    environment:
      <<: *umask-tz-puid-pgid
      VERSION: docker 
      PLEX_CLAIM: $PLEX_CLAIM
      PLEX_PGID: $PGID
      PLEX_PUID: $PUID
    devices:
      # Intel acceleration hardware enable
      - /dev/dri:/dev/dri 
    volumes:
      - $DAPPDATA/plex/:/config/:rw
      - $DMEDIA/tv/:/tv/:rw
      - $DMEDIA/movies/:/movies/rw
  transmission:
    <<: *common-keys-apps
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      <<: *umask-tz-puid-pgid
    volumes:
      - $DAPPDATA/transmission/:/config/:rw
      - $DMEDIA/downloads/:/downloads/:rw
      - $DSHARED/watch/:/watch/:rw

  ## ---------- Management ---------- ##
  homarr:
    <<: *common-keys-apps
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DAPPDATA/homarr/config/:/app/data/config/:rw
      - $DAPPDATA/homarr/icons/:/app/public/icons/:rw
  portainer:
    <<: *common-keys-dns-core
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      <<: *default-tz-puid-pgid
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DAPPDATA/portainer/:/data/:rw
  traefik:
    <<: *common-keys-core
    container_name: traefik
    image: traefik:latest
    environment:
      <<: default-tz-puid-pgid
      CF_API_EMAIL: $CLOUDFLARE_EMAIL
      CF_API_KEY: $CLOUDFLARE_API_KEY
      DOMAIN: $DOMAIN
      TRUSTED_IPS: $CLOUDFLARE_IPS,$LOCAL_IPS
      LOG_LEVEL: $LOG_LEVEL 
    ports:
      - 80:80/tcp 
      - 443:443/tcp 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DAPPDATA/traefik/acme.json:/acme.json:rw
      - $DOPT/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - $DOPT/traefik/rules/:/rules/:ro
      - $DLOGS/traefik/:/logs/:rw
      - $DSHARED/:/shared/:rw
  filebrowser:
    <<: *common-keys-core 
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    environment:
      <<: *default-tz-puid-pgid
    user: $PUID:$PGID
    volumes:
      - $DMEDIA/:/data/:rw
      - $DAPPDATA/filebrowser/:/config/:rw
  watchtower:
    <<: *common-keys-core
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      <<: *default-tz-puid-pgid
      WATCHTOWER_CLEANUP: $WATCHTOWER_CLEANUP
      WATCHTOWER_INCLUDE_RESTARTING: $WATCHTOWER_INCLUDE_RESTARTING
      WATCHTOWER_SCHEDULE: $WATCHTOWER_SCHEDULE
      WATCHTOWER_LOG_LEVEL: $LOG_LEVEL
      WATCHTOWER_ROLLING_RESTART: $WATCHTOWER_ROLLING_RESTART
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  ## ---------- Home Automatization ---------- ##
  mosquitto-client:
    <<: *common-keys-core
    container_name: mosquitto-client
    image: emqx/mqttx-web:latest
    environment:
      <<: *default-tz-puid-pgid
  zigbee2mqtt:
    <<: *common-keys-core
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    environment:
      <<: *default-tz-puid-pgid
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /run/udev:/run/udev:ro
      - $DAPPDATA/zigbee2mqtt/:/app/data/:rw
      - $DSCRIPT/searchtty.sh:/app/searchtty.sh:ro 
  homeassitant:
    <<: *common-keys-core
    container_name: homeassitant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      <<: *default-tz-puid-pgid
      HC_IGNORE_SSL: true
    privileged: true
    container_name:
      - /etc/localtime:/etc/localtime:ro 
      - /run/dbus:/run/dbus:ro 
      - $DAPPDATA/homeassitant/:/config/:rw
  
  ## ---------- Tools ---------- ##
  librespeed:
  znc:
  thelounge:
  mariadb:
  mongodb:
  cloudflared:
