permit_join: false
mqtt:
  base_topic: '!secrets.yaml base_topic'
  server: '!secrets.yaml server'
  user: '!secrets.yaml user'
  password: '!secrets.yaml password'
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key:
    - 23
    - 177
    - 248
    - 136
    - 113
    - 96
    - 102
    - 240
    - 124
    - 121
    - 74
    - 76
    - 221
    - 54
    - 22
    - 194
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
homeassistant: true
devices:
  '0x54ef4410009141e6':
    friendly_name: Entrance
  '0x54ef44100091550f':
    friendly_name: Table
  '0x54ef4410009130f2':
    friendly_name: Living Room
  '0x00178801090570ae':
    friendly_name: Bedroom
